spring.application.name=demo_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/User
spring.datasource.username=postgres
spring.datasource.password=Bhanu@1435
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=50MB

spring.servlet.multipart.max-request-size=50MB

server.port=8082